export const CATEGORIES = [
  "Back Chains",
  "Body Chains",
  "Shoulder Chains",
  "Anklets",
  "Eyeglasses Chains",
  "Bracelets",
  "Bikini Clip Chains",
  "Belly Chains",
  "Necklaces",
] as const;

export type Category = (typeof CATEGORIES)[number];

export type Product = {
  id: string;
  name: string;
  price: number;
  currency: string;
  category: Category;
  description: string;
  images: string[];                          // default (gold or first) images
  variantImages?: Record<string, string[]>;  // { "Gold Tone": [img1, img2], "Silver Tone": [img1, img2] }
  video?: string;                            // plays on hover (muted, looped)
  variantVideos?: Record<string, string>;    // { "Gold Tone": "/video.mp4", "Silver Tone": "/video.mp4" }
  featured: boolean;
  variants?: string[];
  etsy_url?: string;
  amazon_url?: string;
};

export const products: Product[] = [
  {
    id: "back-body-chain-wedding",
    name: "Back Body Chain — Wedding",
    price: 29.99,
    currency: "EUR",
    category: "Back Chains",
    description: "A delicate, dainty back body chain handcrafted for weddings and special occasions. Adjustable fit, tarnish-resistant stainless steel.",
    images: ["/images/products/lifestyle-2.jpg"],
    featured: true,
    variants: ["Gold Tone", "Silver Tone"],
  },
  {
    id: "waist-chain",
    name: "Dainty Waist Chain",
    price: 24.99,
    currency: "EUR",
    category: "Belly Chains",
    description: "Ultra-thin waist chain with adjustable extender. Water-resistant and made to be worn every day.",
    images: ["/images/products/lifestyle-1.jpg"],
    featured: true,
    variants: ["Gold Tone", "Silver Tone"],
  },
  {
    id: "pearl-anklet",
    name: "Pearl Anklet",
    price: 22.99,
    currency: "EUR",
    category: "Anklets",
    description: "Dual-strand pearl and gold chain anklet. 21cm base with 5cm adjustable extender. Handmade in stainless steel.",
    images: ["/images/products/lifestyle-3.jpg"],
    featured: true,
    variants: ["Gold Tone", "Silver Tone"],
  },
  {
    id: "arm-chain",
    name: "Arm Chain Bracelet",
    price: 19.99,
    currency: "EUR",
    category: "Body Chains",
    description: "Minimalist arm chain that wraps gracefully around your upper arm. Adjustable, lightweight and comfortable.",
    images: ["/images/products/lifestyle-4.jpg"],
    featured: false,
    variants: ["Gold Tone", "Silver Tone"],
  },

  // ── ANKLETS ─────────────────────────────────────────────────────────────────

  {
    id: "butterfly-anklet",
    name: "Butterfly Anklet",
    price: 27.50,
    currency: "EUR",
    category: "Anklets",
    description: "A dainty gold butterfly charm anklet made from 316L stainless steel that won't tarnish or irritate. Adjustable length so it sits perfectly on any ankle.",
    images: [
      "/images/products/butterfly-anklet-1.jpg",
      "/images/products/butterfly-anklet-2.jpg",
      "/images/products/butterfly-anklet-3.jpg",
      "/images/products/butterfly-anklet-4.jpg",
    ],
    featured: true,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "evil-eye-anklet",
    name: "Evil Eye Anklet",
    price: 30.00,
    currency: "EUR",
    category: "Anklets",
    description: "A delicate gold chain anklet featuring a pink evil eye charm, handcrafted in 316L stainless steel for lasting wear. The adjustable fit makes it perfect for layering at the beach or every day.",
    images: [
      "/images/products/evil-eye-anklet-1.jpg",
      "/images/products/evil-eye-anklet-2.jpg",
      "/images/products/evil-eye-anklet-3.jpg",
      "/images/products/evil-eye-anklet-4.jpg",
    ],
    video: "/images/products/evil-eye-anklet.mov",
    featured: true,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "foot-chain",
    name: "Dainty Foot Chain",
    price: 30.00,
    currency: "EUR",
    category: "Anklets",
    description: "A barely-there foot chain that wraps from ankle to toe, made from waterproof 316L stainless steel. Great for beach holidays and everyday wear — it won't rust or discolour.",
    images: [
      "/images/products/foot-chain-1.jpg",
      "/images/products/foot-chain-2.jpg",
      "/images/products/foot-chain-3.jpg",
      "/images/products/foot-chain-4.jpg",
    ],
    video: "/images/products/foot-chain.mp4",
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "double-ankle-wrap",
    name: "Barefoot Sandal Ankle Wrap",
    price: 32.50,
    currency: "EUR",
    category: "Anklets",
    description: "A dainty barefoot sandal hand chain that wraps around the ankle and drapes across the foot. Made from adjustable 316L stainless steel — perfect for summer festivals and beach looks.",
    images: [
      "/images/products/double-ankle-wrap-1.jpg",
      "/images/products/double-ankle-wrap-2.jpg",
      "/images/products/double-ankle-wrap-3.jpg",
      "/images/products/double-ankle-wrap-4.jpg",
    ],
    video: "/images/products/double-ankle-wrap.mp4",
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "pearl-barefoot-sandal",
    name: "Pearl Barefoot Sandal",
    price: 40.00,
    currency: "EUR",
    category: "Anklets",
    description: "A pearl-strand foot chain that drapes elegantly from ankle to toe. Handmade with real freshwater pearls and 316L stainless steel — ideal for beach weddings and summer events.",
    images: [
      "/images/products/foot-chain-pearl-1.jpg",
      "/images/products/foot-chain-pearl-2.jpg",
      "/images/products/foot-chain-pearl-3.jpg",
    ],
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "gemstone-starsign-anklet",
    name: "Gemstone Star Sign Anklet",
    price: 30.00,
    currency: "EUR",
    category: "Anklets",
    description: "A waterproof gold anklet featuring a natural gemstone and your choice of zodiac sign charm, made from 316L stainless steel. Adjustable and personalised — a thoughtful gift for anyone who loves their star sign.",
    images: [
      "/images/products/gemstone-starsign-anklet-1.jpg",
      "/images/products/gemstone-starsign-anklet-2.jpg",
      "/images/products/gemstone-starsign-anklet-3.jpg",
      "/images/products/gemstone-starsign-anklet-4.jpg",
    ],
    video: "/images/products/gemstone-starsign-anklet.mov",
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "birthstone-anklet",
    name: "Birthstone Anklet",
    price: 27.50,
    currency: "EUR",
    category: "Anklets",
    description: "A personalised birthstone anklet in gold-tone 316L stainless steel, featuring a dainty gemstone charm in your birth month colour. Adjustable and tarnish-resistant for everyday wear.",
    images: [
      "/images/products/gemstone-anklet-1.jpg",
      "/images/products/gemstone-anklet-2.jpg",
      "/images/products/gemstone-anklet-3.jpg",
      "/images/products/gemstone-anklet-4.jpg",
    ],
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "layered-pearl-stack-anklet",
    name: "Layered Pearl Stack Anklet",
    price: 35.00,
    currency: "EUR",
    category: "Anklets",
    description: "A gold layered pearl anklet with a stacked pearl and chain design in 316L stainless steel. The multi-strand look is timeless for summer and the adjustable extender fits any ankle.",
    images: [
      "/images/products/layered-pearl-anklet-1.jpg",
      "/images/products/layered-pearl-anklet-2.jpg",
      "/images/products/layered-pearl-anklet-3.jpg",
      "/images/products/layered-pearl-anklet-4.jpg",
    ],
    video: "/images/products/layered-pearl-anklet.mov",
    featured: true,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "initial-anklet",
    name: "Initial Letter Anklet",
    price: 30.00,
    currency: "EUR",
    category: "Anklets",
    description: "A personalised initial anklet in gold 316L stainless steel with your chosen letter charm. Adjustable and waterproof — a meaningful gift that lasts.",
    images: [
      "/images/products/letter-anklet-1.jpg",
      "/images/products/letter-anklet-2.jpg",
      "/images/products/letter-anklet-3.jpg",
      "/images/products/letter-anklet-4.jpg",
    ],
    video: "/images/products/letter-anklet.mov",
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "single-pearl-anklet",
    name: "Single Pearl Gold Anklet",
    price: 27.50,
    currency: "EUR",
    category: "Anklets",
    description: "A minimalist gold ankle bracelet with a single freshwater pearl drop, handcrafted in 316L stainless steel. The clean, dainty design pairs well with everything from flip-flops to heels.",
    images: [
      "/images/products/pearl-anklet-1.png",
      "/images/products/pearl-anklet-2.png",
      "/images/products/pearl-anklet-3.png",
      "/images/products/pearl-anklet-4.png",
    ],
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "zodiac-anklet",
    name: "Zodiac Anklet",
    price: 27.50,
    currency: "EUR",
    category: "Anklets",
    description: "A handmade stainless steel anklet featuring your zodiac constellation charm in gold tone. Adjustable and tarnish-free, it makes a personal everyday accessory or a meaningful gift.",
    images: [
      "/images/products/zodiac-anklet-1.jpg",
      "/images/products/zodiac-anklet-2.jpg",
      "/images/products/zodiac-anklet-3.jpg",
      "/images/products/zodiac-anklet-4.jpg",
    ],
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },

  // ── BELLY CHAINS ─────────────────────────────────────────────────────────────

  {
    id: "belly-chain-cross",
    name: "Cross Belly Chain",
    price: 32.00,
    currency: "EUR",
    category: "Belly Chains",
    description: "A gold body chain with a dainty cross pendant, made from waterproof 316L stainless steel. Sits elegantly at the waist and adjusts to any size — great for layering over bikinis or bare skin.",
    images: [
      "/images/products/belly-chain-cross-1.jpg",
      "/images/products/belly-chain-cross-2.jpg",
      "/images/products/belly-chain-cross-3.jpg",
      "/images/products/belly-chain-cross-4.jpg",
    ],
    video: "/images/products/belly-chain-cross.mov",
    featured: true,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "belly-chain-3-pearls",
    name: "Pearl Belly Chain",
    price: 30.00,
    currency: "EUR",
    category: "Belly Chains",
    description: "A boho pearl belly chain with three freshwater pearl accents, handmade in tarnish-resistant 316L stainless steel. Available in gold and silver tone, adjustable to sit anywhere on the waist.",
    images: [
      "/images/products/belly-chain-pearl-gold-1.jpg",
      "/images/products/belly-chain-pearl-gold-2.jpg",
      "/images/products/belly-chain-pearl-gold-3.jpg",
    ],
    variantImages: {
      "Gold Tone": [
        "/images/products/belly-chain-pearl-gold-1.jpg",
        "/images/products/belly-chain-pearl-gold-2.jpg",
        "/images/products/belly-chain-pearl-gold-3.jpg",
      ],
      "Silver Tone": [
        "/images/products/belly-chain-pearl-silver-1.jpg",
      ],
    },
    variantVideos: {
      "Gold Tone": "/images/products/belly-chain-pearl-gold.mp4",
      "Silver Tone": "/images/products/belly-chain-pearl-silver.mp4",
    },
    featured: true,
    variants: ["Gold Tone", "Silver Tone"],
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "zodiac-belly-chain",
    name: "Zodiac Belly Chain",
    price: 28.00,
    currency: "EUR",
    category: "Belly Chains",
    description: "A gold zodiac belly chain in 316L stainless steel with a miniature star sign charm. Adjustable to fit any waist and water-resistant — perfect for wearing to the beach or on holiday.",
    images: [
      "/images/products/belly-chain-zodiac-1.jpg",
      "/images/products/belly-chain-zodiac-2.png",
      "/images/products/belly-chain-zodiac-3.png",
    ],
    video: "/images/products/belly-chain-zodiac.mov",
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "turquoise-beaded-belly-chain",
    name: "Turquoise Beaded Waist Chain",
    price: 40.00,
    currency: "EUR",
    category: "Belly Chains",
    description: "A vibrant turquoise beaded gold waist chain that channels full boho beach energy. Made with 316L stainless steel hardware, adjustable, and lightweight enough to wear all summer.",
    images: [
      "/images/products/blue-beaded-belly-chain-1.jpg",
      "/images/products/blue-beaded-belly-chain-2.jpg",
      "/images/products/blue-beaded-belly-chain-3.png",
    ],
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "dainty-silver-belly-chain",
    name: "Dainty Silver Belly Chain",
    price: 25.00,
    currency: "EUR",
    category: "Belly Chains",
    description: "An ultra-fine silver-tone bikini belly chain in 316L stainless steel that sits delicately at the waist. Completely waterproof and adjustable — designed for everyday wear and beach trips.",
    images: [
      "/images/products/dainty-belly-chain-silver-1.jpg",
      "/images/products/dainty-belly-chain-silver-2.jpg",
      "/images/products/dainty-belly-chain-silver-3.jpg",
      "/images/products/dainty-belly-chain-silver-4.jpg",
    ],
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "double-belly-zodiac",
    name: "Double Belly Chain with Zodiac",
    price: 37.00,
    currency: "EUR",
    category: "Belly Chains",
    description: "A yoga-inspired double belly chain with a personalised zodiac pendant, made from 316L stainless steel. The layered two-strand design adds dimension and moves beautifully with your body.",
    images: [
      "/images/products/double-belly-zodiac-1.jpg",
      "/images/products/double-belly-zodiac-2.jpg",
      "/images/products/double-belly-zodiac-3.jpg",
      "/images/products/double-belly-zodiac-4.jpg",
    ],
    video: "/images/products/double-belly-zodiac.mov",
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "layered-belly-butterfly",
    name: "Layered Butterfly Belly Chain",
    price: 35.00,
    currency: "EUR",
    category: "Belly Chains",
    description: "A gold minimalist layered belly chain with a turquoise butterfly charm in 316L stainless steel. The double-strand silhouette drapes softly at the waist and is fully adjustable.",
    images: [
      "/images/products/double-belly-butterfly-1.jpg",
      "/images/products/double-belly-butterfly-2.jpg",
      "/images/products/double-belly-butterfly-3.jpg",
      "/images/products/double-belly-butterfly-4.jpg",
    ],
    video: "/images/products/double-belly-butterfly.mov",
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "double-belly-stainless",
    name: "Waterproof Double Belly Chain",
    price: 32.00,
    currency: "EUR",
    category: "Belly Chains",
    description: "A waterproof 1.5mm double-strand gold waist chain made from solid 316L stainless steel that never tarnishes. Adjustable to wear at the waist or hips — a summer essential.",
    images: [
      "/images/products/double-belly-stainless-1.jpg",
      "/images/products/double-belly-stainless-2.jpg",
      "/images/products/double-belly-stainless-3.jpg",
      "/images/products/double-belly-stainless-4.jpg",
    ],
    video: "/images/products/double-belly-stainless.mov",
    featured: true,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "mila-belly-chain",
    name: "Mila Belly Chain",
    price: 32.00,
    currency: "EUR",
    category: "Belly Chains",
    description: "The Mila is a gold boho belly chain in 316L stainless steel with a fine, barely-there silhouette. Adjustable to sit at the waist or hip — perfect over a bikini or tucked into high-waisted jeans.",
    images: [
      "/images/products/mila-belly-chain-1.jpg",
      "/images/products/mila-belly-chain-2.jpg",
      "/images/products/mila-belly-chain-3.jpg",
      "/images/products/mila-belly-chain-4.jpg",
    ],
    video: "/images/products/mila-belly-chain.mov",
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "shell-belly-chain",
    name: "Cowrie Shell Belly Chain",
    price: 33.50,
    currency: "EUR",
    category: "Belly Chains",
    description: "A cowrie shell waist chain with an all-natural boho aesthetic, made with 316L stainless steel for durability. The shells are individually set along the chain and the length is fully adjustable.",
    images: [
      "/images/products/shell-belly-chain-1.jpg",
      "/images/products/shell-belly-chain-2.jpg",
      "/images/products/shell-belly-chain-3.jpg",
      "/images/products/shell-belly-chain-4.jpg",
    ],
    video: "/images/products/shell-belly-chain.mov",
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "silver-double-belly",
    name: "Silver Layered Belly Chain",
    price: 30.00,
    currency: "EUR",
    category: "Belly Chains",
    description: "A silver-tone layered belly chain crafted from 316L stainless steel with a clean, minimal look. Adjustable double strands that sit beautifully at the waist for everyday and beach wear.",
    images: [
      "/images/products/silver-double-belly-1.png",
      "/images/products/silver-double-belly-2.png",
      "/images/products/silver-double-belly-3.png",
    ],
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "silver-single-belly",
    name: "Silver Single Belly Chain",
    price: 20.00,
    currency: "EUR",
    category: "Belly Chains",
    description: "A fine silver waist chain in 316L stainless steel — waterproof, adjustable, and made to be worn in and out of the water. The single-strand design is effortlessly understated.",
    images: [
      "/images/products/silver-single-belly-1.png",
      "/images/products/silver-single-belly-2.png",
      "/images/products/silver-single-belly-3.png",
    ],
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "ella-belly-chain",
    name: "Ella Disk Belly Chain",
    price: 40.00,
    currency: "EUR",
    category: "Belly Chains",
    description: "The Ella is a minimalist chain belt with polished disk links in 316L stainless steel, designed to double as a dress accessory or bikini chain. Adjustable length, silver or gold tone.",
    images: [
      "/images/products/ella-belly-chain-1.jpg",
      "/images/products/ella-belly-chain-2.jpg",
      "/images/products/ella-belly-chain-3.jpg",
    ],
    video: "/images/products/ella-belly-chain.mov",
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "stainless-layered-belly",
    name: "Stainless Steel Layered Belly Chain",
    price: 32.00,
    currency: "EUR",
    category: "Belly Chains",
    description: "A multi-layered stainless steel waist chain in gold tone that stacks beautifully at the midriff. Fully waterproof 316L steel, adjustable, and designed for daily wear through any season.",
    images: [
      "/images/products/stainless-layered-belly-1.jpg",
      "/images/products/stainless-layered-belly-2.jpg",
      "/images/products/stainless-layered-belly-3.jpg",
      "/images/products/stainless-layered-belly-4.jpg",
    ],
    video: "/images/products/stainless-layered-belly.mov",
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },

  // ── BACK CHAINS ──────────────────────────────────────────────────────────────

  {
    id: "back-lariat-gemstone",
    name: "Gemstone Back Lariat",
    price: 32.00,
    currency: "EUR",
    category: "Back Chains",
    description: "A personalised back necklace featuring a natural gemstone drop on a delicate lariat-style chain. Made from 316L stainless steel and adjustable to sit perfectly across the back of any open-back outfit.",
    images: [
      "/images/products/back-lariat-gemstone-1.jpg",
      "/images/products/back-lariat-gemstone-2.jpg",
      "/images/products/back-lariat-gemstone-3.jpg",
    ],
    video: "/images/products/back-lariat-gemstone.mov",
    featured: true,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "backdrop-pearl-back",
    name: "Pearl Wedding Back Necklace",
    price: 30.00,
    currency: "EUR",
    category: "Back Chains",
    description: "A bridal back necklace with pearl accents that drapes elegantly down an open back. Handmade in 316L stainless steel with an adjustable clasp — designed for weddings, engagements, and special occasions.",
    images: [
      "/images/products/backdrop-pearl-back-1.jpg",
      "/images/products/backdrop-pearl-back-2.jpg",
      "/images/products/backdrop-pearl-back-3.jpg",
      "/images/products/backdrop-pearl-back-4.jpg",
    ],
    video: "/images/products/backdrop-pearl-back.mov",
    featured: true,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "backwards-farah",
    name: "Dainty Backdrop Back Necklace",
    price: 40.00,
    currency: "EUR",
    category: "Back Chains",
    description: "The Farah is a dainty gold backdrop necklace that frames the back with a single delicate chain. Made from 316L stainless steel and adjustable for a perfect fit — effortlessly elevated for any occasion.",
    images: [
      "/images/products/backwards-farah-1.jpg",
      "/images/products/backwards-farah-2.jpg",
      "/images/products/backwards-farah-3.jpg",
      "/images/products/backwards-farah-4.jpg",
    ],
    video: "/images/products/backwards-farah.mov",
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "backwards-kendal",
    name: "Kendal Bridal Back Necklace",
    price: 40.00,
    currency: "EUR",
    category: "Back Chains",
    description: "A fine bridal back necklace with a long lariat drop for open-back wedding dresses. Crafted from 316L stainless steel with an adjustable design that works on any neckline.",
    images: [
      "/images/products/backwards-kendal-1.jpg",
      "/images/products/backwards-kendal-2.jpg",
      "/images/products/backwards-kendal-3.jpg",
      "/images/products/backwards-kendal-4.jpg",
    ],
    video: "/images/products/backwards-kendal.mov",
    featured: true,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "backwards-butterfly-back",
    name: "Butterfly Festival Back Necklace",
    price: 40.00,
    currency: "EUR",
    category: "Back Chains",
    description: "A statement gold back necklace with a butterfly pendant made for festivals and open-back tops. The 316L stainless steel chain drapes gracefully and is fully adjustable for any body.",
    images: [
      "/images/products/backwards-butterfly-1.jpg",
      "/images/products/backwards-butterfly-2.jpg",
      "/images/products/backwards-butterfly-3.jpg",
      "/images/products/backwards-butterfly-4.jpg",
    ],
    video: "/images/products/backwards-butterfly.mov",
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "backwards-kendal-layer",
    name: "Layered Back Body Chain",
    price: 45.00,
    currency: "EUR",
    category: "Back Chains",
    description: "A layered back body chain for weddings and formal events, featuring two interlaced chains in 316L stainless steel. The draped silhouette adds dimension to any open-back look and adjusts for a perfect fit.",
    images: [
      "/images/products/backwards-kendal-layer-1.jpg",
      "/images/products/backwards-kendal-layer-2.jpg",
      "/images/products/backwards-kendal-layer-3.jpg",
      "/images/products/backwards-kendal-layer-4.jpg",
    ],
    video: "/images/products/backwards-kendal-layer.mp4",
    featured: true,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "backwards-kendal-pearl",
    name: "Pearl Back Necklace",
    price: 40.00,
    currency: "EUR",
    category: "Back Chains",
    description: "A pearl back necklace for weddings and beach occasions, with a freshwater pearl drop on an adjustable 316L stainless steel chain. The minimalist design pairs beautifully with both bridal and casual styles.",
    images: [
      "/images/products/backwards-kendal-pearl-1.jpg",
      "/images/products/backwards-kendal-pearl-2.jpg",
      "/images/products/backwards-kendal-pearl-3.jpg",
      "/images/products/backwards-kendal-pearl-4.jpg",
    ],
    video: "/images/products/backwards-kendal-pearl.mov",
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "pearl-farah-layered",
    name: "Gold Pearl Backdrop Necklace",
    price: 45.00,
    currency: "EUR",
    category: "Back Chains",
    description: "A gold pearl backdrop necklace with a strand of pearls cascading down the spine. Made from 316L stainless steel with a fully adjustable fit — a striking piece for open-back evening wear.",
    images: [
      "/images/products/pearl-farah-layered-1.jpg",
      "/images/products/pearl-farah-layered-2.jpg",
      "/images/products/pearl-farah-layered-3.jpg",
    ],
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "pearl-farah-back",
    name: "Pearl Strand Back Necklace",
    price: 40.00,
    currency: "EUR",
    category: "Back Chains",
    description: "A delicate gold back necklace with a full pearl strand drop for weddings and formal occasions. Handcrafted in 316L stainless steel — adjustable, tarnish-resistant, and designed to last.",
    images: [
      "/images/products/pearl-farah-back-1.jpg",
      "/images/products/pearl-farah-back-2.jpg",
    ],
    video: "/images/products/pearl-farah-back.mov",
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "v-back-necklace",
    name: "V-Back Pearl Necklace",
    price: 35.00,
    currency: "EUR",
    category: "Back Chains",
    description: "A minimalist pearl back necklace with bra-clip attachment points for a secure, invisible fit under any dress. Made from 316L stainless steel — a practical and elegant solution for open-back styles.",
    images: [
      "/images/products/v-back-necklace-1.jpg",
      "/images/products/v-back-necklace-2.jpg",
      "/images/products/v-back-necklace-3.jpg",
    ],
    video: "/images/products/v-back-necklace.mov",
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
  {
    id: "pearl-back-lariat",
    name: "Handmade Pearl Back Lariat",
    price: 45.00,
    currency: "EUR",
    category: "Back Chains",
    description: "A handmade pearl back lariat necklace with a long cascading pearl drop, crafted from 316L stainless steel. Perfect for weddings and open-back eveningwear — every piece is made by hand.",
    images: [
      "/images/products/pearl-back-lariat-1.jpg",
      "/images/products/pearl-back-lariat-2.jpg",
      "/images/products/pearl-back-lariat-3.jpg",
    ],
    video: "/images/products/pearl-back-lariat.mov",
    featured: false,
    etsy_url: "https://www.etsy.com/shop/bodystrandseu",
  },
];
