import { productSeo } from "@/lib/seo-overrides";
import Link from "next/link";
import titlePhrases from "@/data/product-title-phrases.json";
import { products, INFOGRAPHIC_IMAGES, type Product } from "@/lib/products";
import { getShippingRate, COUNTRY_GROUPS, ALL_COUNTRIES } from "@/lib/shipping";
import { notFound } from "next/navigation";
import ProductPageClient from "@/components/ProductPageClient";
import CompleteTheLook from "@/components/CompleteTheLook";
import YouMayAlsoLike from "@/components/YouMayAlsoLike";
import RecentlyViewed from "@/components/RecentlyViewed";
import { type Review } from "@/data/category-reviews";
import customerReviewsRaw from "@/data/customer-reviews.json";

const CUSTOMER_REVIEWS = customerReviewsRaw as Record<string, Review[]>;
const ALL_REAL_REVIEWS: Review[] = Object.values(CUSTOMER_REVIEWS).flat();

// Permanent per-product title phrase: "<Name> | <phrase> | Bodystrands". Generated by
// scripts/product-title-phrases.mjs from the searches Google already shows each product
// (or its category) for in Search Console plus the research keywords — evergreen only.
// Replaced a fixed phrase pool assigned by hash (Oct 2, 2026), which gave e.g. the Chain
// Waist Belt "Belly Chain for Spring Break" in October. Seasonal/occasion searches are
// targeted by /gifts, /christmas, blog posts and Pinterest instead of product titles.
// New products have no Search Console history yet, so until the GSC-driven script is run
// for them (`node scripts/product-title-phrases.mjs <gsc.json> --only <id>`), this builds
// an automatic fallback from the product's own flags/category rather than shipping a bare,
// untargeted category name (e.g. a christmas:true product gets "Christmas <Category>"
// immediately on launch, not weeks later once it has earned real search data).
function pickSuffix(product: Product): string {
  const known = (titlePhrases as Record<string, string>)[product.id];
  if (known) return known;
  if (product.christmas) return `Christmas ${product.category}`;
  if (product.plusSize) return `Plus Size ${product.category}`;
  return product.category;
}

// Google truncates SERP snippets around 155-160 chars. The old version appended a fixed
// 66-char boilerplate sentence to every product's altText, regularly pushing the total to
// 170-190 chars and reading as padding rather than a unique clickable snippet. This keeps
// the per-product altText as the dominant content and appends only a short price+trust tag,
// truncating on a word boundary if the altText alone is already near the limit.
function buildMetaDescription(altText: string | undefined, description: string, priceLabel: string): string {
  const base = (altText ?? description).trim();
  const suffix = ` ${priceLabel} · Waterproof, handmade.`;
  const maxLen = 155;
  const budget = maxLen - suffix.length;
  if (base.length <= budget) return `${base}${suffix}`;
  const cut = base.slice(0, budget);
  const lastSpace = cut.lastIndexOf(" ");
  const trimmed = (lastSpace > 40 ? cut.slice(0, lastSpace) : cut).trimEnd();
  return `${trimmed}…${suffix}`;
}

export async function generateStaticParams() {
  return products.map((p) => ({ id: p.id }));
}

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const product = products.find((p) => p.id === id);
  if (!product) return {};

  // Best image: first variant's first photo, or fallback to images[]
  const firstImage =
    (product.variants?.[0] && product.variantImages?.[product.variants[0]]?.[0]) ||
    product.images?.[0] ||
    "/images/og-image.jpg";

  const url = `https://www.bodystrands.com/shop/${product.id}`;
  const symbol = product.currency === "EUR" ? "€" : product.currency === "GBP" ? "£" : "$";
  const priceLabel = `${symbol}${product.price.toFixed(2)}`;
  const suffix = pickSuffix(product);
  const seo = productSeo(product.id);
  const metaDescription = seo?.description ?? buildMetaDescription(product.altText, product.description, priceLabel);

  return {
    title: seo?.title ?? `${product.name} | ${suffix} | Bodystrands`,
    description: metaDescription,
    alternates: { canonical: `/shop/${product.id}` },
    openGraph: {
      title: `${product.name} | ${suffix} — ${priceLabel}`,
      description: metaDescription,
      url,
      type:     "website",
      siteName: "Bodystrands",
      images: [{ url: firstImage, width: 1200, height: 1200, alt: product.altText ?? product.name }],
    },
    twitter: {
      card:        "summary_large_image",
      title:       `${product.name} | ${suffix} — ${priceLabel}`,
      description: metaDescription,
      images:      [firstImage],
    },
  };
}

export default async function ProductPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const product = products.find((p) => p.id === id);
  if (!product) notFound();

  // JSON-LD structured data for Google Shopping rich results
  const perProductInfographics = new Set(product.infographicImages ?? []);
  const isInfographic = (src: string) => INFOGRAPHIC_IMAGES.has(src) || perProductInfographics.has(src);

  const allImages = (
    product.gallery
      ? product.gallery
      : product.variants?.length && product.variantImages
        ? product.variants.flatMap((v) => product.variantImages![v] ?? [])
        : (product.images ?? [])
  ).filter((src) => !isInfographic(src));

  const firstImage = product.images?.[0] || allImages[0] || "/images/og-image.jpg";

  // Merchant listing shipping details — one entry per shipping zone, using the same
  // rate table the checkout route uses (lib/shipping.ts) so this can't drift out of sync.
  const shippingDetails = COUNTRY_GROUPS.map((group) => {
    const rate = getShippingRate(group.countries[0].code, 0); // base (non-free) rate for the zone
    return {
      "@type": "OfferShippingDetails",
      shippingRate: {
        "@type":  "MonetaryAmount",
        value:    (rate.amount / 100).toFixed(2),
        currency: "EUR",
      },
      shippingDestination: {
        "@type":        "DefinedRegion",
        addressCountry: group.countries.map((c) => c.code),
      },
      deliveryTime: {
        "@type": "ShippingDeliveryTime",
        handlingTime: {
          "@type":   "QuantitativeValue",
          minValue:  1,
          maxValue:  2,
          unitCode:  "DAY",
        },
        transitTime: {
          "@type":  "QuantitativeValue",
          minValue: rate.deliveryMin,
          maxValue: rate.deliveryMax,
          unitCode: "DAY",
        },
      },
    };
  });

  // Only this product's OWN reviews (exact productId match) ever feed rating/review
  // schema — never the "other X in this category" or shop-wide tiers shown on the page,
  // since those aren't genuinely about this product and Google's review-markup
  // guidelines require the review to be about the specific item being marked up.
  const ownReviews = ALL_REAL_REVIEWS.filter((r) => r.productId === product.id);
  const aggregateRating = ownReviews.length > 0 ? {
    "@type":     "AggregateRating",
    ratingValue: (ownReviews.reduce((s, r) => s + r.rating, 0) / ownReviews.length).toFixed(1),
    reviewCount: ownReviews.length,
  } : undefined;
  const reviewSchema = ownReviews.map((r) => ({
    "@type": "Review",
    author: { "@type": "Person", name: r.name },
    datePublished: new Date(r.date).toISOString().slice(0, 10),
    reviewRating: { "@type": "Rating", ratingValue: r.rating, bestRating: 5, worstRating: 1 },
    reviewBody: r.text,
  }));

  const hasMerchantReturnPolicy = {
    "@type":               "MerchantReturnPolicy",
    applicableCountry:     ALL_COUNTRIES,
    returnPolicyCategory:  "https://schema.org/MerchantReturnFiniteReturnWindow",
    merchantReturnDays:    14,
    returnMethod:          "https://schema.org/ReturnByMail",
    returnFees:            "https://schema.org/ReturnShippingFees",
  };

  const productJsonLd = {
    "@context": "https://schema.org",
    "@type": "Product",
    name:          product.name,
    description:   product.description,
    sku:           product.id,
    image:         allImages.length > 0 ? allImages : [firstImage],
    material:      "Stainless Steel",
    itemCondition: "https://schema.org/NewCondition",
    brand: {
      "@type": "Brand",
      name:    "Bodystrands",
    },
    category:      product.category,
    ...(product.variants?.length ? {
      color: product.variants.join(", "),
    } : {}),
    ...(aggregateRating ? { aggregateRating } : {}),
    ...(reviewSchema.length > 0 ? { review: reviewSchema } : {}),
    offers: {
      "@type":          "Offer",
      url:              `https://www.bodystrands.com/shop/${product.id}`,
      price:            product.price.toFixed(2),
      priceCurrency:    product.currency ?? "EUR",
      availability:     "https://schema.org/InStock",
      itemCondition:    "https://schema.org/NewCondition",
      validFrom:        new Date().toISOString().slice(0, 10),
      priceValidUntil:  new Date(Date.now() + 365 * 86400 * 1000).toISOString().slice(0, 10),
      shippingDetails,
      hasMerchantReturnPolicy,
      seller: {
        "@type": "Organization",
        name:    "Bodystrands",
      },
    },
  };

  const breadcrumbJsonLd = {
    "@context": "https://schema.org",
    "@type":    "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home",  item: "https://www.bodystrands.com" },
      { "@type": "ListItem", position: 2, name: "Shop",  item: "https://www.bodystrands.com/shop" },
      { "@type": "ListItem", position: 3, name: product.name, item: `https://www.bodystrands.com/shop/${product.id}` },
    ],
  };

  return (
    <div className="pt-32 md:pt-36 pb-24">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }} />

      <div className="max-w-7xl mx-auto px-6 md:px-10">

        {/* Breadcrumb */}
        <nav className="mb-6 md:mb-12 flex items-center gap-3 text-[0.55rem] tracking-[0.2em] uppercase text-[#8C7B6E]">
          <Link href="/" className="hover:text-[#A0622A] transition-colors">Home</Link>
          <span>/</span>
          <Link href="/shop" className="hover:text-[#A0622A] transition-colors">Shop</Link>
          <span>/</span>
          <span className="text-[#2C2220]">{product.name}</span>
        </nav>

        <ProductPageClient product={product} />
        <CompleteTheLook product={product} />
        <YouMayAlsoLike product={product} />
        <RecentlyViewed excludeId={product.id} />
      </div>
    </div>
  );
}
